### PR TITLE
[INVALID]

### LINKED ISSUE #4: Feature request: Permission nodes
Hi! Could you add perm nodes? I think players mustn't use /refarena command, it should be for OPs.
Perms:
onevsone.refarena - Allows players use /refarena
ovevsone.match - Allows players use /match

### PR DESCRIPTION
**Pull request by ivand-sykt**
Itt'll bebetter. Sorry for bad english :(
Closes #4

### CODE REVIEW

**Comment by Minifixio** [comment]
Thanks you very much guy ! I think I will add it in the next update if PocketMine accept it because I have submitted an update but they didn't accept it and I don't know why.

**Comment by ivand-sykt** [comment]
Test it before please :)

**Comment by Minifixio** [comment]
Ok, thanks ! :) But I'm a bit messy right now ...

**Comment by ivand-sykt** [comment]
It's no longer needed.

**Comment by Minifixio** [comment]
OK I added it before

**Pull request closed without merging**
