### PR TITLE
Update Arena.php

### PR DESCRIPTION
**Pull request by bjorguv**

### CODE REVIEW

**Comment by bjorguv** [comment]
first PHP ever written would be a cool addition to the plug-in if what I wrote was correct

**Comment by Minifixio** [comment]
True, I never think to change the gamemode. Thanks !

**Comment by bjorguv** [comment]
Say yea you might have to add the code because I'm not very good but it would be cool :)

**Comment by Minifixio** [comment]
Yes of course that is a good start and :)

**Comment by Minifixio** [comment]
and I think it's a good addition

**Pull request merged**
