### PR TITLE
Update Arena.php

### PR DESCRIPTION
**Pull request by bjorguv**
woops! set changed gm to creative :P

### CODE REVIEW

**Comment by Minifixio** [comment]
OK thanks xD

**Comment by bjorguv** [comment]
do you know if it works?

**Comment by Minifixio** [comment]
Oh you didn't test. I'm gonna try it tomorrow

**Comment by bjorguv** [comment]
I'll try to test asap but for some reason I can't /makeplugin with dev tool

**Comment by bjorguv** [comment]
ok well it crashed the server for me when I try to /refarena so idk.

**Comment by robske110** [comment]
Crash report?

**Comment by robske110** [comment]
But this has nothing to do with /refarena

**Comment by Minifixio** [comment]
Yes

**Comment by Minifixio** [comment]
I'm gonna try it

**Comment by bjorguv** [comment]
Well I didn't say it had to do with ref arena but server crashed when I did it

**Comment by bjorguv** [comment]
I know nothing about php would be better to just put it in yourself and delete what I wrote

**Comment by Minifixio** [comment]
OK thanks :) but I'm very busy so I'll try to test it this afternoon

**Pull request merged**
