### PR TITLE
Fix crash reported by @Tolo0

### PR DESCRIPTION
**Pull request by robske110**

### CODE REVIEW

**Comment by Minifixio** [comment]
Why is it a bad practice to use Server::getInstance ?

**Comment by robske110** [comment]
Because it's an property (Go and ask @PEMapModder for more info)
And ryou have to revert this commit:

**Comment by robske110** [comment]
https://github.com/Minifixio/pocketmine-1vs1-plugin/commit/2b98cf87a58c82cba2a97728b412ae9737ecdee4

**Comment by PEMapModder** [comment]
Static property.

**Pull request closed without merging**
