### PR TITLE
Updated ArenaManagaer.php

### PR DESCRIPTION
**Pull request by applqpak**
Multiple Bad Practises. I've fixed most. Please work on this, otherwise, nice plugin!

### CODE REVIEW

**Comment by robske110** [comment]
Why isn't that merged yet?
It is an MUST

**Comment by Minifixio** [comment]
I didn't try but I trust him.

**Comment by robske110** [comment]
I will test this this evening!

**Comment by Minifixio** [comment]
It will not work as the getServer() method is not referenced in to the ArenaManager class ? Did someone test it ?

**Comment by robske110** [comment]
use pocketmine\server?

**Comment by robske110** [comment]
And can you please check my pull request out?

**Comment by robske110** [comment]
REVERT THID NOT WORKING

**Comment by PocketKiller** [comment]
Revert this, you are not having PluginBase as a parent.

**Comment by robske110** [comment]
He can pass the object via constructor

**Comment by PocketKiller** [comment]
I know.

**Comment by robske110** [comment]
image
This is the shortest way to do it (i think lol)

**Comment by PocketKiller** [comment]
wait for the image to upload...

**Comment by robske110** [comment]
Now

**Pull request merged**
