### PR TITLE
Update Arena.php

### PR DESCRIPTION
**Pull request by ghost**
just a litte suggestion :+1:

### CODE REVIEW

**Comment by ifvictr** [comment]
@SavionLegendZzz You don't know what you're doing. There's no such file as `pocketmine\Plugin`. Go learn some more before you try to help people, because right now you're just making a bunch of useless PRs.

**Comment by ghost** [comment]
i do know what i am doing 1.i was rushing it 2. i meant todo pocketmine\plugin\PluginBase; :D

**Comment by robske110** [comment]
why not closing this?

**Comment by DaPigGuy** [comment]
ArenaManager doesn't even extend PluginBase...

**Pull request closed without merging**
