### PR TITLE
New Food System (SetFood and GiveMoreBread)

### PR DESCRIPTION
**Pull request by robske110**
Theres an optional setFood too!
And I will soon pull request an clickable sign!

### CODE REVIEW

**Comment by robske110** [comment]
Whats up with this?
I am still working on an clickable sign though!

**Comment by robske110** [comment]
What's up with this @Minifixio ?

**Comment by robske110** [comment]
Will this be merged or not? @Minifixio

**Comment by DaPigGuy** [comment]
This is awful, using loops to give 8 of the same item?... Just use $player->getInventory()->addItem(Item::get(Item::BREAD, 0, 8));

**Comment by robske110** [comment]
Oh, missed that #PerformanceIssue
Will be fixed soon

**Comment by robske110** [comment]
@Minifixio Could you please answer this?

**Comment by Minifixio** [comment]
Finally, it's what I did before no ?

**Comment by robske110** [comment]
So you don't want this?

**Comment by Minifixio** [comment]
No it doesn't change anything but thanks.

**Comment by robske110** [comment]
What it doesn't change anything?! It sets the hunger to full and gives 8Bread instead of 1!
It does change stuff!

**Comment by ghost** [comment]
Nah. You only have 3mins to kill. I dont need a bread? @Minifixio , should focus on team vs team & gameround (maybe up to 10 rounds) to make it better gaming.

**Comment by robske110** [comment]
Man, this is to SET THE FOOD TO FULL on game start

**Pull request closed without merging**
